### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by keesfluitman** [xente/loki-logger-handler#8]
Maybe i'm too new in the whole programming world. But the formatter formats records like this:
```
"message": record.msg % record.args,
```
Which always causes a TypeError for me. Since some log messages without any arguments, do not work? I've simple adapted the format class to: 
```
    def format(self, record):
        if record.args:
            message = record.msg % record.args
        else:
            message = record.msg

        formatted = {
            "message": message,
            "timestamp": record.created,
            "process": record.process,
            "thread": record.thread,
            "function": record.funcName,
            "module": record.module,
            "name": record.name,
            "level": record.levelname,
        }
```
What am I overlooking? Im using it in a flask application at the moment.

**Comment by xente** [comment]
I all my test the args are coming as a empty array. I can not reproduce your issue.

logger.debug("Debug message"). It is working 
logger.debug("Debug message", extra={"custom_field": "custom_value"}). It is working 

Can you provide more info about your issue?

Are you using LoggerFormatter or LoguruFormatter?

**Comment by keesfluitman** [comment]
Oke so I started checking a bit. Logs are actually fine. All log entries are added fine. But it still throws the error.
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/logging/handlers.py", line 1583, in _monitor
    self.handle(record)
  File "/usr/lib/python3.12/logging/handlers.py", line 1564, in handle
    handler.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/home/kees/projects/websites/kees-website/Website-Project/loki_logger_handler/loki_logger_handler.py", line 38, in emit
    self._put(self.logger_formatter.format(record))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kees/projects/websites/kees-website/Website-Project/loki_logger_handler/formatters/logger_formatter.py", line 38, in format
    "message": record.msg % record.args,
               ~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
```
I don't get where it's coming from.

**Comment by xente** [comment]
New version has been released https://pypi.org/project/loki-logger-handler/0.1.4/

Can you check if it mitigate your issue?

**Comment by keesfluitman** [comment]
confirm that the getMessage() method solves it.
